### ISSUE TITLE
crash while opening

### ISSUE THREAD

**Issue by SANESSSSSSSSSS** [FossilsArcheologyRevival/FossilsArcheologyRevival#1237]
so, i've downloaded the mod, and...
whenever i open my game...
**it crashes**
it's not missing **llibrary**, because i downloaded
so, why is it crashing?

**Comment by lindstheginj** [comment]
We won’t be able to figure it out unless you provide a crash report.

**Comment by SANESSSSSSSSSS** [comment]
it's not main minecraft launcher, cause brazil is hard to live in but... here it is i think

[01:04:43] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[01:04:44] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[01:04:44] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[01:04:44] [main/DEBUG] [FML]: Injecting tracing printstreams for STDOUT/STDERR.
[01:04:44] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2811 for Minecraft 1.12.2 loading
[01:04:44] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_201, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_201
[01:04:44] [main/DEBUG] [FML]: Java classpath at launch is:
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.12.2-14.23.5.2811\forge-1.12.2-14.23.5.2811.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.2\asm-all-5.2.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\jline\jline\2.13\jline-2.13.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\apache\maven\maven-artifact\3.5.3\maven-artifact-3.5.3.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\tlauncher\patchy\1.1\patchy-1.1.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.1.9.Final\netty-all-4.1.9.Final.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\21.0\guava-21.0.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\tlauncher\authlib\1.5.25\authlib-1.5.25.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.10.22\realms-1.10.22.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\7.1.0\fastutil-7.1.0.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3.jar
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\versions\ForgeOptiFine 1.12.2\ForgeOptiFine 1.12.2.jar
[01:04:44] [main/DEBUG] [FML]: Java library path at launch is:
[01:04:44] [main/DEBUG] [FML]:     C:\Users\rianc\AppData\Roaming\.minecraft\versions\ForgeOptiFine 1.12.2\natives
[01:04:44] [main/DEBUG] [FML]: Determined Minecraft Libraries Root: C:\Users\rianc\AppData\Roaming\.minecraft\libraries
[01:04:44] [main/DEBUG] [FML]: Cleaning up mods folder: C:\Users\rianc\AppData\Roaming\.minecraft\mods
[01:04:44] [main/DEBUG] [FML]: Examining file: fossilsarcheology-8.0.0.jar
[01:04:45] [main/DEBUG] [FML]: Examining file: llibrary-1.7.15-1.12.2.jar
[01:04:45] [main/DEBUG] [FML]: Found existing ContainedDep llibrary-core-1.0.8-1.12.2.jar(net.ilexiconn:llibrary-core:1.0.8-1.12.2) from C:\Users\rianc\AppData\Roaming\.minecraft\mods\memory_repo\net\ilexiconn\llibrary-core\1.0.8-1.12.2\llibrary-core-1.0.8-1.12.2.jar extracted to C:\Users\rianc\AppData\Roaming\.minecraft\mods\llibrary-1.7.15-1.12.2.jar, skipping extraction
[01:04:45] [main/DEBUG] [FML]: Examining file: llibrary-core-1.0.8-1.12.2.jar
[01:04:45] [main/DEBUG] [FML]: Making maven link for net.ilexiconn:llibrary:1.7.15-1.12.2 in memory to C:\Users\rianc\AppData\Roaming\.minecraft\mods\llibrary-1.7.15-1.12.2.jar.
[01:04:45] [main/DEBUG] [FML]: Examining file: OptiFine-1.12.2_HD_U_E3.jar
[01:04:45] [main/DEBUG] [FML]: File already proccessed C:\Users\rianc\AppData\Roaming\.minecraft\mods\memory_repo\net\ilexiconn\llibrary-core\1.0.8-1.12.2\llibrary-core-1.0.8-1.12.2.jar, Skipping
[01:04:45] [main/DEBUG] [FML]: File already proccessed C:\Users\rianc\AppData\Roaming\.minecraft\mods\llibrary-1.7.15-1.12.2.jar, Skipping
[01:04:46] [main/DEBUG] [FML]: Enabling runtime deobfuscation
[01:04:46] [main/DEBUG] [FML]: Instantiating coremod class FMLCorePlugin
[01:04:46] [main/DEBUG] [FML]: Found signing certificates for coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin)
[01:04:46] [main/DEBUG] [FML]: Found certificate e3c3d50c7c986df74c645c0ac54639741c90a557
[01:04:46] [main/DEBUG] [FML]: Added access transformer class net.minecraftforge.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[01:04:46] [main/DEBUG] [FML]: Enqueued coremod FMLCorePlugin
[01:04:46] [main/DEBUG] [FML]: Instantiating coremod class FMLForgePlugin
[01:04:46] [main/DEBUG] [FML]: Found signing certificates for coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin)
[01:04:46] [main/DEBUG] [FML]: Found certificate e3c3d50c7c986df74c645c0ac54639741c90a557
[01:04:46] [main/DEBUG] [FML]: Enqueued coremod FMLForgePlugin
[01:04:46] [main/DEBUG] [FML]: All fundamental core mods are successfully located
[01:04:46] [main/DEBUG] [FML]: Discovering coremods
[01:04:46] [main/INFO] [FML]: Searching C:\Users\rianc\AppData\Roaming\.minecraft\mods for mods
[01:04:46] [main/DEBUG] [FML]:   Adding fossilsarcheology-8.0.0.jar to the mod list
[01:04:46] [main/DEBUG] [FML]:   Adding llibrary-1.7.15-1.12.2.jar to the mod list
[01:04:46] [main/DEBUG] [FML]:   Adding OptiFine-1.12.2_HD_U_E3.jar to the mod list
[01:04:46] [main/DEBUG] [FML]: Examining for coremod candidacy fossilsarcheology-8.0.0.jar
[01:04:46] [main/DEBUG] [FML]: Not found coremod data in fossilsarcheology-8.0.0.jar
[01:04:46] [main/DEBUG] [FML]: Examining for coremod candidacy OptiFine-1.12.2_HD_U_E3.jar
[01:04:46] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine-1.12.2_HD_U_E3.jar
[01:04:46] [main/DEBUG] [FML]: Examining for coremod candidacy llibrary-core-1.0.8-1.12.2.jar
[01:04:46] [main/TRACE] [FML]: Adding llibrary-core-1.0.8-1.12.2.jar to the list of known coremods, it will not be examined again
[01:04:46] [main/DEBUG] [FML]: Instantiating coremod class LLibraryPlugin
[01:04:46] [main/TRACE] [FML]: coremod named llibrary is loading
[01:04:46] [main/DEBUG] [FML]: The coremod net.ilexiconn.llibrary.server.core.plugin.LLibraryPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[01:04:46] [main/DEBUG] [FML]: Found signing certificates for coremod llibrary (net.ilexiconn.llibrary.server.core.plugin.LLibraryPlugin)
[01:04:46] [main/DEBUG] [FML]: Found certificate b9f30a813bee3b9dd5652c460310cfcd54f6b7ec
[01:04:46] [main/DEBUG] [FML]: Enqueued coremod llibrary
[01:04:46] [main/DEBUG] [FML]: Examining for coremod candidacy llibrary-1.7.15-1.12.2.jar
[01:04:46] [main/DEBUG] [FML]: Not found coremod data in llibrary-1.7.15-1.12.2.jar
[01:04:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[01:04:46] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[01:04:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[01:04:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[01:04:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[01:04:46] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[01:04:46] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[01:04:46] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[01:04:46] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[01:04:46] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\rianc\AppData\Roaming\.minecraft\mods\OptiFine-1.12.2_HD_U_E3.jar
[01:04:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[01:04:46] [main/DEBUG] [FML]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[01:04:46] [main/TRACE] [FML]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[01:04:47] [main/TRACE] [FML]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[01:04:47] [main/TRACE] [FML]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[01:04:47] [main/TRACE] [FML]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[01:04:47] [main/DEBUG] [FML]: Injection complete
[01:04:47] [main/DEBUG] [FML]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[01:04:47] [main/DEBUG] [FML]: Running coremod plugin FMLCorePlugin
[01:04:50] [main/DEBUG] [FML]: Read 1111 binary patches
[01:04:50] [main/DEBUG] [FML]: Loading deobfuscation resource /deobfuscation_data-1.12.2.lzma with 36083 records
[01:04:54] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[01:04:54] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[01:04:54] [main/DEBUG] [FML]: Coremod plugin class FMLCorePlugin run successfully
[01:04:54] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[01:04:54] [main/DEBUG] [FML]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[01:04:54] [main/DEBUG] [FML]: Injection complete
[01:04:54] [main/DEBUG] [FML]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[01:04:54] [main/DEBUG] [FML]: Running coremod plugin FMLForgePlugin
[01:04:54] [main/DEBUG] [FML]: Coremod plugin class FMLForgePlugin run successfully
[01:04:54] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[01:04:54] [main/DEBUG] [FML]: Loaded 214 rules from AccessTransformer config file forge_at.cfg
[01:04:54] [main/DEBUG] [FML]: Loaded 3 rules from AccessTransformer mod jar file C:\Users\rianc\AppData\Roaming\.minecraft\mods\fossilsarcheology-8.0.0.jar!META-INF/fossil_at.cfg

[01:04:54] [main/DEBUG] [FML]: Loaded 10 rules from AccessTransformer mod jar file C:\Users\rianc\AppData\Roaming\.minecraft\mods\llibrary-1.7.15-1.12.2.jar!META-INF/llibrary_at.cfg

[01:04:54] [main/DEBUG] [FML]: Validating minecraft
[01:04:56] [main/DEBUG] [FML]: Minecraft validated, launching...
[01:04:56] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[01:04:56] [main/DEBUG] [FML]: Injecting coremod llibrary \{net.ilexiconn.llibrary.server.core.plugin.LLibraryPlugin\} class transformers
[01:04:56] [main/TRACE] [FML]: Registering transformer net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
[01:04:57] [main/TRACE] [FML]: Registering transformer net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
[01:04:57] [main/DEBUG] [LLibrary Core]: Found runtime patcher net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
[01:04:57] [main/DEBUG] [FML]: Injection complete
[01:04:57] [main/DEBUG] [FML]: Running coremod plugin for llibrary \{net.ilexiconn.llibrary.server.core.plugin.LLibraryPlugin\}
[01:04:57] [main/DEBUG] [FML]: Running coremod plugin llibrary
[01:04:57] [main/DEBUG] [FML]: Coremod plugin class LLibraryPlugin run successfully
[01:04:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[01:04:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[01:04:57] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[01:04:57] [main/DEBUG] [LLibrary Core]: Found no method mapping for java/lang/String/format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
[01:04:57] [main/DEBUG] [LLibrary Core]: Found no method mapping for net/minecraft/client/model/ModelBiped/<init>(FZ)V
[01:04:57] [main/DEBUG] [LLibrary Core]: Found no method mapping for net/minecraft/client/renderer/entity/RenderPlayer/<init>(Lnet/minecraft/client/renderer/entity/RenderManager;Z)V
[01:04:58] [main/DEBUG] [LLibrary Core]: Found no method mapping for net/minecraftforge/client/ForgeHooksClient/handleCameraTransforms(Lnet/minecraft/client/renderer/block/model/IBakedModel;Lnet/minecraft/client/renderer/block/model/ItemCameraTransforms$TransformType;Z)Lnet/minecraft/client/renderer/block/model/IBakedModel;
[01:04:58] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[01:05:03] [main/DEBUG] [LLibrary Core]: Patching class net/minecraft/server/MinecraftServer
[01:05:03] [main/DEBUG] [LLibrary Core]:    Patching method run()V
[01:05:03] [main/DEBUG] [LLibrary Core]: Found no method mapping for net/ilexiconn/llibrary/server/core/patcher/LLibraryHooks/getTickRate()J
[01:05:03] [main/DEBUG] [LLibrary Core]: Found no method mapping for net/ilexiconn/llibrary/server/core/patcher/LLibraryHooks/getTickRate()J
[01:05:03] [main/DEBUG] [LLibrary Core]: Found no method mapping for net/ilexiconn/llibrary/server/core/patcher/LLibraryHooks/getTickRate()J
[01:05:03] [main/DEBUG] [LLibrary Core]: Found no method mapping for net/ilexiconn/llibrary/server/core/patcher/LLibraryHooks/getTickRate()J
[01:05:04] [main/DEBUG] [LLibrary Core]: Patching class net/minecraftforge/client/ForgeHooksClient
[01:05:04] [main/DEBUG] [LLibrary Core]:    Patching method handleCameraTransforms(Lnet/minecraft/client/renderer/block/model/IBakedModel;Lnet/minecraft/client/renderer/block/model/ItemCameraTransforms$TransformType;Z)Lnet/minecraft/client/renderer/block/model/IBakedModel;
[01:05:04] [main/DEBUG] [LLibrary Core]: Found no method mapping for net/ilexiconn/llibrary/server/core/patcher/LLibraryHooks/providePerspectiveContext(Lnet/minecraft/client/renderer/block/model/ItemCameraTransforms$TransformType;)V
[01:05:04] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraftforge/client/ForgeHooksClient.invalidateLog4jThreadCache()V @65: invokeinterface
  Reason:
    Type 'java/lang/Object' (current frame, stack[2]) is not assignable to 'java/lang/Throwable'
  Current Frame:
    bci: @65
    flags: { }
    locals: { 'java/lang/Object' }
    stack: { 'org/apache/logging/log4j/Logger', 'java/lang/String', 'java/lang/Object' }
  Bytecode:
    0x0000000: 1305 b413 05b6 b605 ba4b 1305 bc13 05be
    0x0000010: b605 ba4c 2a04 b605 c42b 04b6 05c4 2a01
    0x0000020: b605 c5c0 0124 01b6 0128 2b01 b605 c5c0
    0x0000030: 0124 01b6 0128 a700 104b b202 eb13 05c9
    0x0000040: 2ab9 05cd 0300 b1                      
  Exception Handler Table:
    bci [0, 54] => handler: 57
    bci [0, 54] => handler: 57
  Stackmap Table:
    same_locals_1_stack_item_frame(@57,Object[#4])
    append_frame(@70,Object[#4])

	at net.minecraft.client.Minecraft.<init>(Minecraft.java:335) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
[01:05:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[01:05:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[01:05:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[01:05:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[01:05:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[01:05:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[01:05:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Alex-the-666** [comment]
>not main minecraft launcher, cause brazil is hard to live in but

> Caused by: java.lang.VerifyError: Bad type on operand stack

This is caused by some extremely messed up JDK code... I suggest you install minecraft legally if you want to play the game.

**Comment by SANESSSSSSSSSS** [comment]
got it to work again
