### ISSUE TITLE
Help ASAP

### ISSUE THREAD

**Issue by KillJoy13** [FossilsArcheologyRevival/FossilsArcheologyRevival#1343]
Okay so im trying to get my modded server to work but this keeps popping up
java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:25)
at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
We appear to be missing one or more essential library files.
You will need to add them to your server before FML and Forge will run successfully.
What am i missing? 
Now forge isnt working?????? 1.7.10 version? i dont get it.

**Comment by Alex-the-666** [comment]
1.7.10 issues no longer supported.

**Comment by KillJoy13** [comment]
then how do i fix it so it is supported? cause thats bull if i cant.

**Comment by lindstheginj** [comment]
What he means is, we are not working on 1.7.10 bugs anymore because we are working on 1.12.2 updates now. I'd recommend updating to the latest mod version.
