### ISSUE TITLE
Help ASAP

### ISSUE THREAD

**Issue by KillJoy13** [FossilsArcheologyRevival/FossilsArcheologyRevival#1344]
Okay so im trying to get my modded server to work but this keeps popping up
java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:25)
at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
We appear to be missing one or more essential library files.
You will need to add them to your server before FML and Forge will run successfully.
What am i missing?
Now forge isnt working?????? 1.7.10 version? i dont get it. I know its not supported anymore but, how do you fix it so it is. since somebody decided to close my fucking question when they shouldnt of.

**Comment by lindstheginj** [comment]
Knock it off. What “not supported” means is, we are no longer fixing 1.7.10 issues because they are from an outdated version of the mod. You can’t just “fix it so it is supported,” because you’re still playing 1.7.10. Please keep any bug reports for the 1.12.2 version only. And please bite your tongue when you want to sass our main coder who is just doing his job.

**Comment by CactusKingIII** [comment]
They closed your issue exactly when they should have, stop being an entitled cunt before you get blocked from the GitHub
