### ISSUE TITLE
Server crash during loading with 8.0.1

### ISSUE THREAD

**Issue by ArkenorOakshadow** [FossilsArcheologyRevival/FossilsArcheologyRevival#1358]
Forge 2836.

A client with the same mods loaded up fine. I deleted the config files from both machines as instructed.

`Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fossils and Archeology Revival (fossil)
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.EntityList.func_192839_a(Ljava/lang/String;)Ljava/lang/Class;
    at fossilsarcheology.server.util.FoodMappings.addToEntityMappings(FoodMappings.java:399)
    at fossilsarcheology.server.util.FoodMappings.addMeatEntity(FoodMappings.java:593)
    at fossilsarcheology.server.util.FossilFoodMappings.register(FossilFoodMappings.java:161)
    at fossilsarcheology.server.ServerProxy.onPostInit(ServerProxy.java:225)
    at fossilsarcheology.Revival.onPostInit(Revival.java:93)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
`

[crash-2019-06-07_23.17.50-server.txt](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/files/3267810/crash-2019-06-07_23.17.50-server.txt)

**Comment by Sunconure11** [comment]
I think I know why this is happening, but @Alex-the-666 would have to get on it.

It's an issue with a system he showed me that allows one to specify mobs from other mods as valid fodder. Something in it is screwed.

**Comment by ArkenorOakshadow** [comment]
Is it perhaps being caused by a particular mod's meat?
In case it is any use,these are the mods I'm using that I think would have new meats:
[ANGRY PIXEL] The Betweenlands
Animania
Aquaculture
Atum
Chococraft
Exotic Birds
Familiar Fauna
Grimoire of Gaia
Harvestcraft
Ice and Fire
Mystical Wildlife
NetherEX
Primitive Mobs
Reptile Mod
Totemic
Twilight Forest
Zoocraft Discoveries

**Comment by Sunconure11** [comment]
We know the cause. I'm just waiting for Alex to get on it.

**Comment by Cecco42** [comment]
I got the same issue

**Comment by nephatrine** [comment]
@Cecco42  It's already a known issue. I don't think they need us to all chime in that it still exists.

**Comment by kreezxil** [comment]
I see that alex fixed the issue 13 days ago with https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/commit/60e8e66a8bd2c914b09b7f961ba521335314f942 

What's the ETA on the push to curseforge for this?

**Comment by Raptorofwar** [comment]
The devs don't give out release dates.

**Comment by Sunconure11** [comment]
Ten duotrigintillion years

**Comment by kreezxil** [comment]
@raptorofwar some devs do, therefore you statement is inherently false.

**Comment by lindstheginj** [comment]
@kreezxil yes but he was talking specifically about us and WE don’t.

**Comment by kreezxil** [comment]
@lindstheginj if I updated my pack once every 3 to 6 months I'd be happy
with that. You can ask Alex how often I update my pack. I can get you lots
of bug reports if you had a shorter release schedule instead of having to
choke on ton of them because you thought you had everything fixed in your
long dev cycle.

**Comment by Gift-of-Names** [comment]
Hate to break it to you, but the development of the mod does not revolve around you. The devs do not give out release dates, that is their official policy. Whining about it will not change that fact.

**Comment by Raptorofwar** [comment]
Everyone can be friends, here. Let's all calm down. I'ma leave this picture here.
![image](https://user-images.githubusercontent.com/42446863/60280924-c18a9500-98b8-11e9-8d8a-daf4d73aff2c.png)

**Comment by Sunconure11** [comment]
Fuck it, I'm going to lock this.
