### ISSUE TITLE
Horse Embryo Birth Crashing my Game

### ISSUE THREAD

**Issue by Liam-dinogirl34** [FossilsArcheologyRevival/FossilsArcheologyRevival#1495]
I was playing the game and I was just moving stuff in my chests when it crashed? It wasn't lagging, and didn't seem to give any indication that it was going to crash. Minecraft has never crashed on my computer before, so I think it could be an issue with the mod. I have the latest version. Only the one world is doing this, the mod works fine and loads fine with my other worlds. I'll leave the crash report below.

EDIT: It has finally opened after many tries (which is a huge relief, because I love that world). I believe it had something to do with me impregnating my mule. That's the only thing I can think of the game crashing for. I'm not going to close this, just because it's important, and I want other players to see this, but from now on, my mules aren't allowed to have kids lol.

EDIT 2: After doing an experiment (and my game crashing again after I tried to make my llama give birth to a horse). It appears that only donkey's can give birth to horses (they turn out mules), as well as horses without the game crashing. It crashed when my llama gave birth and when my mule did, but not when the donkey or horse did. My cow was able to give birth to my second llama however, so I think it's just the horse embryo having this issue. Here's to hoping my favorite save file comes back to me (I have an extra copy, don't worry)!

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 8/7/19 8:26 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at fossilsarcheology.server.event.FossilLivingEvent.growEntity(FossilLivingEvent.java:173)
	at fossilsarcheology.server.event.FossilLivingEvent.onEntityLiving(FossilLivingEvent.java:96)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_44_FossilLivingEvent_onEntityLiving_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:580)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.AbstractHorse.func_70071_h_(AbstractHorse.java:682)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at fossilsarcheology.server.event.FossilLivingEvent.growEntity(FossilLivingEvent.java:173)
	at fossilsarcheology.server.event.FossilLivingEvent.onEntityLiving(FossilLivingEvent.java:96)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_44_FossilLivingEvent_onEntityLiving_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:580)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.AbstractHorse.func_70071_h_(AbstractHorse.java:682)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: minecraft:mule (net.minecraft.entity.passive.EntityMule)
	Entity ID: 366450
	Entity Name: Mule
	Entity's Exact location: -377.10, 63.00, 244.48
	Entity's Block location: World: (-378,63,244), Chunk: (at 6,3,4 in -24,15; contains blocks -384,0,240 to -369,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Dino Park
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -1133391918978730104
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-232,64,208), Chunk: (at 8,4,0 in -15,13; contains blocks -240,0,208 to -225,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2430498 game time, 4060861 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 135742 (now: false), thunder time: 11564 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 465417096 bytes (443 MB) / 1040187392 bytes (992 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | llibrary  | 1.7.19       | llibrary-1.7.19-1.12.2.jar    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil    | 8.0.2        | fossilsarcheology-8.0.2.jar   | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Alex-the-666** [comment]
java.lang.ClassCastException: net.minecraft.entity.passive.EntityHorse cannot be cast to net.minecraft.entity.passive.EntityLlama

important issue
