### ISSUE TITLE
Crash issue version 7.3.2 game 1.7.10

### ISSUE THREAD

**Issue by EspressoSage** [FossilsArcheologyRevival/FossilsArcheologyRevival#1788]
I always have had this mod crash when I use it, it might be because of the amount of mods I am running at a time, I currently have been running 58 items not including fossils and archaeology revival I have been trying to play a version of 1.7.10 mystic mesa:
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 6/12/20 5:12 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/TextureMap
	at fastcraft.Z.<clinit>(F:11)
	at fastcraft.ab.<clinit>(F:16125)
	at fastcraft.HC.j(F:70)
	at net.minecraft.client.renderer.texture.DynamicTexture.func_110564_a(DynamicTexture.java)
	at net.minecraft.client.renderer.texture.TextureUtil.<clinit>(TextureUtil.java:460)
	at net.minecraft.client.shader.Framebuffer.func_147605_b(Framebuffer.java:104)
	at net.minecraft.client.shader.Framebuffer.func_147613_a(Framebuffer.java:56)
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:37)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.TextureMap
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at fastcraft.Z.<clinit>(F:11)
	at fastcraft.ab.<clinit>(F:16125)
	at fastcraft.HC.j(F:70)
	at net.minecraft.client.renderer.texture.DynamicTexture.func_110564_a(DynamicTexture.java)
	at net.minecraft.client.renderer.texture.TextureUtil.<clinit>(TextureUtil.java:460)
	at net.minecraft.client.shader.Framebuffer.func_147605_b(Framebuffer.java:104)
	at net.minecraft.client.shader.Framebuffer.func_147613_a(Framebuffer.java:56)
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:37)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 75347480 bytes (71 MB) / 167772160 bytes (160 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Launched Version: 1.7.10-Forge10.13.4.1566-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 2000 GL version 3.1.0 - Build 9.17.10.4459, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Clear+Glass+Pack+1.11+or+1.12.zip, 1.12.2-BiomesOPlenty.zip, MysticMesaResourcePackV1.3.zip]
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Mushroomsock** [comment]
You need [llibrary](https://www.curseforge.com/minecraft/mc-mods/llibrary/files/2319767) to run this mod.

**Comment by SagePeris** [comment]
> You need [llibrary](https://www.curseforge.com/minecraft/mc-mods/llibrary/files/2319767) to run this mod.

I tried running it with llibrary, it didn't work, I updated the crash log to the crash with llibrary in my pack

**Comment by lindstheginj** [comment]
Looks like you’re playing 1.7.10. Which mod version do you have?

**Comment by EspressoSage** [comment]
mod version 7.3.2 I am playing in game 1.7.10 forge and 58 other mods

**Comment by EspressoSage** [comment]
If you were wondering I fixed this issue from removing optifine and then I loaded only library and archaeology, it worked, then I slowly added in my mods until I had no more, and between every few mods I would test out the world.
