### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by crakiMDH** [FossilsArcheologyRevival/FossilsArcheologyRevival#417]
I was playing around with the Mammoth, and then I crashed. The mammoth was asleep, and I pulled him with a lead. Then I crashed.

**Comment by iLexiconn** [comment]
thanks for the crash log you provided

**Comment by crakiMDH** [comment]
1) No need to be so mean.

2) I forgot the crash report thing. Here it is:

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 7/17/16 2:47 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at fossilsarcheology.server.entity.mob.Flock.onUpdate(Flock.java:65)
	at fossilsarcheology.server.entity.EntityPrehistoric.func_70636_d(EntityPrehistoric.java:587)
	at fossilsarcheology.server.entity.mob.EntityMammoth.func_70636_d(EntityMammoth.java:161)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at fossilsarcheology.server.entity.EntityPrehistoric.func_70071_h_(EntityPrehistoric.java:628)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at fossilsarcheology.server.entity.mob.Flock.onUpdate(Flock.java:65)
	at fossilsarcheology.server.entity.EntityPrehistoric.func_70636_d(EntityPrehistoric.java:587)
	at fossilsarcheology.server.entity.mob.EntityMammoth.func_70636_d(EntityMammoth.java:161)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at fossilsarcheology.server.entity.EntityPrehistoric.func_70071_h_(EntityPrehistoric.java:628)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: fossil.Mammoth (fossilsarcheology.server.entity.mob.EntityMammoth)
	Entity ID: 167
	Entity Name: Mammoth
	Entity's Exact location: 280.93, 5.32, 288.85
	Entity's Block location: World: (280,5,288), Chunk: (at 8,0,0 in 17,18; contains blocks 272,0,288 to 287,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.16, -0.33, -0.30
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: All dinos attacking animations!
	All players: 1 total; [EntityPlayerMP['epic_slayer_999'/185, l='All dinos attacking animations!', x=278.44, y=9.11, z=287.50]]
	Chunk stats: ServerChunkCache: 1015 Drop: 0
	Level seed: -5719857986718867633
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (100,4,154), Chunk: (at 4,0,10 in 6,9; contains blocks 96,0,144 to 111,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 28783 game time, 13000 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 52283 (now: false), thunder time: 41844 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.9.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 200856792 bytes (191 MB) / 538898432 bytes (513 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	securitycraft{v1.8.1} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.1.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	chisel{2.4.0.38} [Chisel 2] (Chisel2-2.4.0.38.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8 - MC 1.7.10.jar) 
	UCHIJAAAA	ctmlib{1.0.0.3} [CTMLib] (Chisel2-2.4.0.38.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	llibrary{1.4.1} [LLibrary] (llibrary-1.4.1-1.7.10.jar) 
	UCHIJAAAA	fossil{7.3.0} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.3.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.1} [Malisis' Doors] (malisisdoors-1.7.10-1.13.1.jar) 
	UCHIJAAAA	mcheli{0.9.3} [MC Helicopter] (mcheli) 
	UCHIJAAAA	XaeroMinimap{1.6.1.2} [Xaero's Minimap] (xaeros_minimap_v1.6.1.2_Forge_1.7.10.jar) 
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['epic_slayer_999'/185, l='All dinos attacking animations!', x=278.44, y=9.11, z=287.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
