### ISSUE TITLE
Clicking recipe book produces a crash

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#592]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  llibrary (llibrary-core-1.0.4-1.12.2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 6/27/18 2:04 PM
Description: Updating screen events

java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: net.minecraft.item.crafting.ShapedRecipes@7e5d59f1 Name: tabula:tabularasa
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:53)
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:35)
	at net.minecraft.client.gui.recipebook.RecipeList.func_194210_a(SourceFile:34)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.lambda$updateCollections$0(GuiRecipeBook.java:161)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook$$Lambda$242/467292272.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193003_g(GuiRecipeBook.java:159)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193014_a(GuiRecipeBook.java:96)
	at net.minecraft.client.gui.inventory.GuiInventory.func_146284_a(SourceFile:182)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73864_a(SourceFile:160)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:53)
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:35)
	at net.minecraft.client.gui.recipebook.RecipeList.func_194210_a(SourceFile:34)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.lambda$updateCollections$0(GuiRecipeBook.java:161)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook$$Lambda$242/467292272.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193003_g(GuiRecipeBook.java:159)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193014_a(GuiRecipeBook.java:96)
	at net.minecraft.client.gui.inventory.GuiInventory.func_146284_a(SourceFile:182)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73864_a(SourceFile:160)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['GinjaninjaS7'/2591, l='MpServer', x=-6.50, y=71.00, z=-125.50]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-4,64,-124), Chunk: (at 12,4,4 in -1,-8; contains blocks -16,0,-128 to -1,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 9797 game time, 9797 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 58 total; [EntityBat['Bat'/2820, l='MpServer', x=6.42, y=47.41, z=-134.72], EntityWolf['Wolf'/133, l='MpServer', x=56.22, y=63.00, z=-127.19], EntityWolf['Wolf'/134, l='MpServer', x=63.25, y=63.00, z=-134.25], EntityWolf['Wolf'/135, l='MpServer', x=47.67, y=63.00, z=-133.40], EntityWolf['Wolf'/136, l='MpServer', x=53.79, y=62.30, z=-135.46], EntityBat['Bat'/2828, l='MpServer', x=62.83, y=42.05, z=-159.50], EntityBat['Bat'/2830, l='MpServer', x=63.53, y=42.87, z=-153.50], EntityBat['Bat'/2838, l='MpServer', x=24.70, y=37.97, z=-46.25], EntityBat['Bat'/2845, l='MpServer', x=57.75, y=17.10, z=-194.57], EntityBat['Bat'/2849, l='MpServer', x=-4.45, y=18.46, z=-160.16], EntityCreeper['Creeper'/2723, l='MpServer', x=-71.50, y=25.00, z=-57.50], EntitySkeleton['Skeleton'/2725, l='MpServer', x=-41.50, y=43.00, z=-120.50], EntityCreeper['Creeper'/2729, l='MpServer', x=23.50, y=16.00, z=-137.50], EntityZombie['Zombie'/2731, l='MpServer', x=-5.50, y=28.00, z=-69.50], EntityBat['Bat'/2859, l='MpServer', x=-23.76, y=35.23, z=-77.84], EntitySkeleton['Skeleton'/2732, l='MpServer', x=54.50, y=34.00, z=-177.50], EntityBat['Bat'/2860, l='MpServer', x=59.12, y=45.00, z=-67.73], EntitySkeleton['Skeleton'/2733, l='MpServer', x=49.50, y=34.00, z=-173.50], EntitySkeleton['Skeleton'/2734, l='MpServer', x=47.50, y=34.00, z=-172.50], EntityTarSlime['Tar Slime'/1588, l='MpServer', x=-19.93, y=27.00, z=-76.07], EntityBat['Bat'/2745, l='MpServer', x=51.87, y=47.08, z=-78.22], EntityBat['Bat'/2876, l='MpServer', x=42.54, y=48.39, z=-78.39], EntityChicken['Chicken'/72, l='MpServer', x=-76.50, y=63.00, z=-112.50], EntityTarSlime['Tar Slime'/1608, l='MpServer', x=55.02, y=14.96, z=-82.98], EntityChicken['Chicken'/73, l='MpServer', x=-76.50, y=63.00, z=-112.50], EntityTarSlime['Tar Slime'/1609, l='MpServer', x=56.10, y=14.96, z=-80.86], EntityChicken['Chicken'/74, l='MpServer', x=-73.50, y=63.00, z=-110.50], EntitySquid['Squid'/2766, l='MpServer', x=-63.40, y=60.00, z=-134.04], EntitySquid['Squid'/2767, l='MpServer', x=-69.56, y=60.44, z=-133.42], EntityZombieVillager['Zombie Villager'/2770, l='MpServer', x=-85.24, y=42.00, z=-164.50], EntityPlayerSP['GinjaninjaS7'/2591, l='MpServer', x=-6.50, y=71.00, z=-125.50], EntityLatchedRenderer['unknown'/85, l='MpServer', x=-6.50, y=71.00, z=-125.50], EntityBat['Bat'/2783, l='MpServer', x=-60.25, y=31.03, z=-112.25], EntityBat['Bat'/2784, l='MpServer', x=-61.25, y=31.00, z=-110.52], EntitySquid['Squid'/2792, l='MpServer', x=-40.92, y=60.74, z=-83.12], EntityChicken['Chicken'/105, l='MpServer', x=7.84, y=64.00, z=-151.44], EntitySquid['Squid'/2793, l='MpServer', x=-45.41, y=60.33, z=-81.65], EntityChicken['Chicken'/106, l='MpServer', x=2.42, y=68.00, z=-156.23], EntitySquid['Squid'/2794, l='MpServer', x=-44.58, y=61.14, z=-77.04], EntityChicken['Chicken'/107, l='MpServer', x=17.16, y=68.00, z=-156.18], EntityChicken['Chicken'/108, l='MpServer', x=12.50, y=65.00, z=-152.50], EntitySheep['Sheep'/109, l='MpServer', x=12.50, y=75.00, z=-49.50], EntitySheep['Sheep'/110, l='MpServer', x=11.50, y=74.00, z=-48.50], EntitySheep['Sheep'/111, l='MpServer', x=10.50, y=74.00, z=-48.50], EntitySheep['Sheep'/112, l='MpServer', x=11.50, y=74.00, z=-51.50], EntityPig['Pig'/113, l='MpServer', x=36.57, y=75.00, z=-59.73], EntityPig['Pig'/114, l='MpServer', x=35.45, y=75.00, z=-60.55], EntityPig['Pig'/115, l='MpServer', x=35.50, y=75.00, z=-57.50], EntityPig['Pig'/116, l='MpServer', x=38.50, y=74.00, z=-65.50], EntityZombie['Zombie'/2804, l='MpServer', x=15.50, y=38.00, z=-166.50], EntityChicken['Chicken'/117, l='MpServer', x=40.50, y=72.00, z=-202.35], EntityZombie['Zombie'/2805, l='MpServer', x=16.50, y=38.00, z=-166.50], EntityChicken['Chicken'/118, l='MpServer', x=38.90, y=72.00, z=-202.07], EntityChicken['Chicken'/119, l='MpServer', x=41.50, y=72.00, z=-202.50], EntityPig['Pig'/121, l='MpServer', x=44.50, y=75.00, z=-91.50], EntityPig['Pig'/122, l='MpServer', x=44.50, y=75.00, z=-91.50], EntityPig['Pig'/123, l='MpServer', x=42.50, y=75.00, z=-90.50], EntityPig['Pig'/124, l='MpServer', x=42.50, y=75.00, z=-93.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 458232912 bytes (437 MB) / 889192448 bytes (848 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version       | Source                                  | Signature                                |
	|:------ |:--------- |:------------- |:--------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft | 1.12.2        | minecraft.jar                           | None                                     |
	| UCHIJA | mcp       | 9.42          | minecraft.jar                           | None                                     |
	| UCHIJA | FML       | 8.0.99.99     | forge-1.12.2-14.23.3.2655.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge     | 14.23.3.2655  | forge-1.12.2-14.23.3.2655.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | llibrary  | 1.7.14        | llibrary-1.7.14-1.12.2.jar              | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJA | fossil    | 8.0.0-develop | fossilsarcheology-8.0.0-develop (2).jar | None                                     |
	| UCHIJA | ichunutil | 7.1.4         | iChunUtil-1.12.2-7.1.4.jar              | None                                     |
	| UCHIJA | tabula    | 7.0.0         | Tabula-1.12.2-7.0.0.jar                 | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
llibrary (llibrary-core-1.0.4-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4549' Renderer: 'Intel(R) HD Graphics 5500'
	Launched Version: 1.12.2-forge1.12.2-14.23.3.2655
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.4549, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz

**Comment by lindstheginj** [comment]
Only happens on the server and only happens to me... Single player works fine

**Comment by gegy1000** [comment]
This looks like an issue in tabula to me.

**Comment by Alex-the-666** [comment]
this is a tabula issue
